### ISSUE TITLE
M5stick C 

### ISSUE THREAD

**Issue by Cheun1** [mlukasek/M5StickC_NightscoutMon#4]
M5stickC with nightscout follow  Dexcom bridge via heroku is not ok  (on M5 Stack all is ok)
![M5stack  spike follower_nightscout](https://user-images.githubusercontent.com/41595891/102011966-f22deb00-3d47-11eb-8786-82a982ed8847.PNG)
![M5stickC](https://user-images.githubusercontent.com/41595891/102012043-6f596000-3d48-11eb-827a-13304de7cbea.PNG)

**Comment by mlukasek** [comment]
Could you send me the URL where the problem appears to my email, please? I will check. I do not have Dexcom.

**Comment by Cheun1** [comment]
Solved now with the last.INO
